# Generated by Django 3.2.5 on 2021-07-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
